name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  # Since the Windows unit tests take much longer, we run the linux unit tests first and then run the windows unit tests in parallel with NUTs
  linux-unit-tests:
    needs: yarn-lockfile-check
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  windows-unit-tests:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/unitTestsWindows.yml@main
  nuts:
    needs: linux-unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        command:
          - 'yarn test:nuts:deb'
          - 'yarn test:nuts:deploy'
          - 'yarn test:nuts:deploy:metadata:manifest'
          - 'yarn test:nuts:deploy:metadata:metadata-dir'
          - 'yarn test:nuts:deploy:metadata:metadata'
          - 'yarn test:nuts:deploy:metadata:source-dir'
          - 'yarn test:nuts:deploy:metadata:test-level'
          - 'yarn test:nuts:static'
          - 'yarn test:nuts:retrieve'
          - 'yarn test:nuts:delete'
          - 'yarn test:nuts:destructive'
          - 'yarn test:nuts:convert'
          - 'yarn test:nuts:manifest'
          - 'yarn test:nuts:specialTypes'
          - 'yarn test:nuts:tracking'
      fail-fast: false
    with:
      os: ${{ matrix.os }}
      command: ${{ matrix.command }}
